name: clean_architecture_ttd_jsonplaceholder
description: This app for show how to use Clean Architecture TDD and apply it on json Placeholer api.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.6.4
   # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  # Local cache
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
